# Generated by Django 4.2.5 on 2023-09-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VoltageSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cell_id", models.CharField(max_length=16)),
                ("voltage", models.DecimalField(decimal_places=2, max_digits=4)),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
